spring:
  activemq:
  ###MQ连接通讯地址
    broker-url: tcp://127.0.0.1:61616
  ###账号
    user: admin
  ###密码  
    password: admin
  mail:
  ###163邮箱服务器
    host: smtp.163.com
    ###发送人账号
    username: yushengjun6442018@163.com
    ##授权码
    password: yushengjun644
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
    


###自定义队列    
my_queue: springboot2.0-mail
server:
  port: 8082